function xd = pose_d_to_xd(k1,k2,in3,in4,in5,in6,d)
%POSE_D_TO_XD
%    XD = POSE_D_TO_XD(K1,K2,IN3,IN4,IN5,IN6,D)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    13-Apr-2022 16:23:35

R_1_1 = in3(1);
R_1_2 = in3(4);
R_1_3 = in3(7);
R_2_1 = in3(2);
R_2_2 = in3(5);
R_2_3 = in3(8);
R_3_1 = in3(3);
R_3_2 = in3(6);
R_3_3 = in3(9);
p1_1 = in5(1,:);
p1_2 = in5(2,:);
p1_3 = in5(3,:);
p2_1 = in6(1,:);
p2_2 = in6(2,:);
p2_3 = in6(3,:);
t_1 = in4(1,:);
t_2 = in4(2,:);
t_3 = in4(3,:);
t2 = d.*p2_1;
t3 = d.*p2_2;
t4 = d.*p2_3;
t5 = d-1.0;
t6 = p1_1.*t5;
t7 = p1_2.*t5;
t8 = p1_3.*t5;
t9 = -t6;
t10 = -t7;
t11 = -t8;
t12 = t2+t9;
t13 = t3+t10;
t14 = t4+t11;
t15 = R_1_1.*t12;
t16 = R_1_2.*t13;
t17 = R_1_3.*t14;
t18 = R_2_1.*t12;
t19 = R_2_2.*t13;
t20 = R_2_3.*t14;
t21 = R_3_1.*t12;
t22 = R_3_2.*t13;
t23 = R_3_3.*t14;
t24 = t15+t16+t17+t_1;
t25 = t18+t19+t20+t_2;
t26 = t21+t22+t23+t_3;
t27 = t24.^2;
t28 = t25.^2;
t29 = t27+t28;
xd = t24.*1.0./t26.^5.*(k2.*t29.^2+t26.^4+k1.*t26.^2.*t29);
