function sol = pat_v_cr_to_d(P1_2_x,P2_2_x,P3_2_x,P4_2_x,cr1)
%PAT_V_CR_TO_D
%    SOL = PAT_V_CR_TO_D(P1_2_X,P2_2_X,P3_2_X,P4_2_X,CR1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    26-Oct-2022 22:05:52

t2 = P4_2_x.*cr1;
t3 = -P3_2_x;
t4 = -P2_2_x.*cr1;
sol = (P3_2_x.*t2+P4_2_x.*t3+P2_2_x.*P4_2_x+P2_2_x.*cr1.*t3)./(P1_2_x.*(P2_2_x+t2+t3+t4));
