function out1 = pat_v_d_to_cr(P1_2_x,P2_2_x,P3_2_x,P4_2_x,d1)
%PAT_V_D_TO_CR
%    OUT1 = PAT_V_D_TO_CR(P1_2_X,P2_2_X,P3_2_X,P4_2_X,D1)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    26-Oct-2022 22:05:52

t2 = P1_2_x.*d1;
t3 = -t2;
out1 = [(P4_2_x+t3).*(P2_2_x-P3_2_x),(P3_2_x+t3).*(P2_2_x-P4_2_x)];
